### ISSUE TITLE
How can i run the code the see it's performance?

### ISSUE THREAD

**Issue by seyednasermoravej** [SabaEskandarian/Clarion#1]
Hi,
I'm trying to run the code, but I have encountered some issues.
The exact arguments that I'm passing to the code are:
4 server/params/five.txt
According to the descriptions, the paramFile you use should have k+1 servers.
I thought the input number of servers must be 4. Am I wrong here?
By the way, after I tried to debug the code step by step, I found out that the code gets stuck at this line:
		conns[i], err = tls.Dial("tcp", addrs[i], conf)
in the server.go file.
In my next attempt, I changed the order of servers from:
5
10
10.142.0.9:4330
10.128.0.3:4331
10.168.0.4:4332
10.128.0.4:4333
10.150.0.2:4334
localhost:4335
localhost:4336
localhost:4337
localhost:4338
localhost:4339
localhost:4340
localhost:4341
PARAMS
to:
5
10
localhost:4335
localhost:4336
localhost:4337
localhost:4338
localhost:4339
10.142.0.9:4330
10.128.0.3:4331
10.168.0.4:4332
10.128.0.4:4333
10.150.0.2:4334
localhost:4340
localhost:4341
PARAMS
In this case, I got the error:
server.go:145: dial tcp 127.0.0.1:4335: connect: connection refused.
I have no idea how I can run the code on my PC.
Please help.

**Comment by SabaEskandarian** [comment]
The code is meant to be run on multiple computers communicating over a network, or one computer running multiple instances of the server code. It looks like you're just running one instance instead of all the necessary ones, so there is no server running, e.g., on port 4335 to receive the connection.

**Comment by seyednasermoravej** [comment]
Yes, thank you for your clue. For those who may be interested in evaluating the performance of the code, I have done the following to test the code on a single PC running Ubuntu 22.04:
0. As it is obvious, build the code. The output will be a "server" file.
1. open the first terminal. in directory "Clarion/server" enter:
`./server 0 params/paramsLocal3.txt`
2. open another terminal. in directory "Clarion/server" enter:
`./server 1 params/paramsLocal3.txt`
3. open another terminal. in directory "Clarion/server" enter:
`./server 2 params/paramsLocal3.txt`
4. open another terminal. in directory "Clarion/server" enter:
`./server -1 params/paramsLocal3.txt`
